Description: Dayo  - S3 bucket for WebApp sourceCode.
###################################
Parameters:
  EnvironmentName:
    Description: Will be prefixed to all resources names.
    Type: String
  BucketName:
    Description: Name of the bucket to store web app source files.
    Type: String
###################################
Resources:
  WebAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
    DeletionPolicy: Delete
###################################
Outputs:
  Bucket:
    Value: !Ref WebAppBucket
    Description: Bucket with sourcefiles
    Export:
      Name: !Sub ${EnvironmentName}-Project2BucketData
